/**
 * Weekly Technical SEO Checks
 * Runs broken link detection and sitemap generation
 */

import { checkBrokenLinks, generateSitemap } from './nextjs_space/lib/seo-automation';
import { writeFileSync, appendFileSync } from 'fs';
import { format } from 'date-fns';
import { sendEmail } from './nextjs_space/lib/email';

async function runTechnicalSEOChecks() {
  const date = format(new Date(), 'yyyy-MM-dd');
  const timestamp = format(new Date(), 'yyyy-MM-dd HH:mm:ss');
  
  console.log(`[${timestamp}] Starting Weekly Technical SEO Checks...`);
  
  try {
    // Step 1 & 2: Check for broken links
    console.log('Step 1: Checking for broken links...');
    const brokenLinksResult = await checkBrokenLinks();
    
    console.log(`Checked ${brokenLinksResult.checked} pages, found ${brokenLinksResult.broken.length} broken links`);
    
    // Step 2: Save broken links if any found
    if (brokenLinksResult.broken.length > 0) {
      const brokenLinksReport = `# Broken Links Report - ${date}

**Generated:** ${timestamp}
**Pages Checked:** ${brokenLinksResult.checked}
**Broken Links Found:** ${brokenLinksResult.broken.length}

## Broken Links

${brokenLinksResult.broken.map((link, index) => {
  const [path, status] = link.split(' (');
  const statusCode = status.replace(')', '');
  return `${index + 1}. **${path}**
   - Status: \`${statusCode}\`
   - URL: https://thebasketballfactoryinc.com${path}`;
}).join('\n\n')}

## Recommended Actions

${brokenLinksResult.broken.length > 5 ? '⚠️ **CRITICAL:** More than 5 broken links detected. Immediate action required.\n\n' : ''}
1. Review each broken link and determine if the page should be:
   - Fixed (if the page should exist)
   - Redirected (if the page has moved)
   - Removed (if the page is no longer needed)

2. Update internal links pointing to these pages

3. Set up proper 301 redirects for moved content

4. Update sitemap after fixes are applied

---
*This report was automatically generated by the SEO Automation System*
`;

      writeFileSync(`/home/ubuntu/seo_automation_logs/broken_links_${date}.md`, brokenLinksReport);
      console.log(`✓ Broken links report saved to /home/ubuntu/seo_automation_logs/broken_links_${date}.md`);
    } else {
      console.log('✓ No broken links found');
    }
    
    // Step 3: Generate sitemap
    console.log('Step 3: Generating XML sitemap...');
    const sitemapXml = await generateSitemap();
    
    if (sitemapXml) {
      // Step 4: Save sitemap
      writeFileSync('/home/ubuntu/rise_as_one_aau/nextjs_space/public/sitemap.xml', sitemapXml);
      console.log('✓ Sitemap generated and saved to /home/ubuntu/rise_as_one_aau/nextjs_space/public/sitemap.xml');
    } else {
      console.error('✗ Failed to generate sitemap');
    }
    
    // Step 5: Log results
    const logEntry = `[${timestamp}] Technical SEO Check Complete
  - Pages Checked: ${brokenLinksResult.checked}
  - Broken Links Found: ${brokenLinksResult.broken.length}
  - Sitemap Generated: ${sitemapXml ? 'Yes' : 'No'}
  - Status: ${brokenLinksResult.broken.length > 5 ? 'ALERT - Critical' : 'OK'}
\n`;
    
    appendFileSync('/home/ubuntu/seo_automation_logs/technical_checks.log', logEntry);
    console.log('✓ Results logged to /home/ubuntu/seo_automation_logs/technical_checks.log');
    
    // Step 6: Send alert email if broken links exceed 5
    if (brokenLinksResult.broken.length > 5) {
      console.log('Step 6: Sending alert email (broken links > 5)...');
      
      const emailHtml = `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; }
    .header { background: #dc2626; color: white; padding: 30px; text-align: center; }
    .alert-box { background: #fee2e2; border-left: 4px solid #dc2626; padding: 20px; margin: 20px 0; }
    .link-list { background: #f9f9f9; padding: 15px; margin: 10px 0; border-radius: 5px; }
    .footer { text-align: center; padding: 20px; color: #666; font-size: 12px; }
  </style>
</head>
<body>
  <div class="header">
    <h1>🚨 Critical SEO Alert</h1>
    <p>Broken Links Detected</p>
  </div>

  <div style="padding: 30px;">
    <div class="alert-box">
      <h2>⚠️ ${brokenLinksResult.broken.length} Broken Links Found</h2>
      <p>Our automated technical SEO check has detected <strong>${brokenLinksResult.broken.length} broken links</strong> on your website. This exceeds the critical threshold of 5 broken links and requires immediate attention.</p>
    </div>

    <h3>📋 Summary</h3>
    <ul>
      <li><strong>Date:</strong> ${date}</li>
      <li><strong>Pages Checked:</strong> ${brokenLinksResult.checked}</li>
      <li><strong>Broken Links:</strong> ${brokenLinksResult.broken.length}</li>
      <li><strong>Severity:</strong> <span style="color: #dc2626;">CRITICAL</span></li>
    </ul>

    <h3>🔗 Broken Links</h3>
    <div class="link-list">
      ${brokenLinksResult.broken.map((link, index) => {
        const [path, status] = link.split(' (');
        const statusCode = status.replace(')', '');
        return `<p><strong>${index + 1}.</strong> ${path} - <code>${statusCode}</code></p>`;
      }).join('')}
    </div>

    <h3>✅ Recommended Actions</h3>
    <ol>
      <li>Review each broken link and determine the appropriate fix</li>
      <li>Set up 301 redirects for moved content</li>
      <li>Update internal links pointing to these pages</li>
      <li>Remove or fix pages that should exist</li>
      <li>Regenerate sitemap after fixes are applied</li>
    </ol>

    <p><strong>Full Report:</strong> Check <code>/home/ubuntu/seo_automation_logs/broken_links_${date}.md</code> for detailed information.</p>
  </div>

  <div class="footer">
    <p>This is an automated alert from The Basketball Factory Inc. SEO Automation System</p>
    <p><a href="https://thebasketballfactoryinc.com/admin/seo">View SEO Dashboard</a></p>
  </div>
</body>
</html>
      `;
      
      try {
        const emailResult = await sendEmail({
          to: 'khouston@thebasketballfactorynj.com',
          subject: `🚨 CRITICAL: ${brokenLinksResult.broken.length} Broken Links Detected`,
          html: emailHtml
        });
        
        if (emailResult.success) {
          console.log('✓ Alert email sent successfully');
        } else {
          console.error('✗ Failed to send alert email:', emailResult.error);
        }
      } catch (emailError) {
        console.error('✗ Error sending alert email:', emailError);
      }
    } else {
      console.log('Step 6: Skipped (broken links <= 5)');
    }
    
    console.log('\n=== Technical SEO Check Complete ===');
    console.log(`Pages Checked: ${brokenLinksResult.checked}`);
    console.log(`Broken Links: ${brokenLinksResult.broken.length}`);
    console.log(`Sitemap: ${sitemapXml ? 'Generated' : 'Failed'}`);
    console.log(`Status: ${brokenLinksResult.broken.length > 5 ? '🚨 CRITICAL' : '✓ OK'}`);
    
  } catch (error) {
    console.error('Error during technical SEO checks:', error);
    
    // Log the error
    const errorLog = `[${timestamp}] Technical SEO Check FAILED
  - Error: ${error instanceof Error ? error.message : String(error)}
\n`;
    appendFileSync('/home/ubuntu/seo_automation_logs/technical_checks.log', errorLog);
    
    process.exit(1);
  }
}

// Run the checks
runTechnicalSEOChecks().catch(console.error);
