import { checkBrokenLinks, generateSitemap } from './lib/seo-automation';
import { sendEmail } from './lib/email';
import { format } from 'date-fns';
import * as fs from 'fs';
import * as path from 'path';

async function runTechnicalSEOCheck() {
  const date = format(new Date(), 'yyyy-MM-dd');
  const logDir = '/home/ubuntu/seo_automation_logs';
  
  // Ensure log directory exists
  if (!fs.existsSync(logDir)) {
    fs.mkdirSync(logDir, { recursive: true });
  }

  console.log('=== Starting Weekly Technical SEO Check ===');
  console.log(`Date: ${date}`);
  
  // Step 1: Check for broken links
  console.log('\n[Step 1] Checking for broken links...');
  const brokenLinksResult = await checkBrokenLinks();
  
  console.log(`Checked ${brokenLinksResult.checked} pages`);
  console.log(`Found ${brokenLinksResult.broken.length} broken links`);
  
  // Step 2: Save broken links if found
  if (brokenLinksResult.broken.length > 0) {
    console.log('\n[Step 2] Saving broken links report...');
    const brokenLinksPath = path.join(logDir, `broken_links_${date}.md`);
    
    const brokenLinksContent = `# Broken Links Report
**Date:** ${date}
**Total Pages Checked:** ${brokenLinksResult.checked}
**Broken Links Found:** ${brokenLinksResult.broken.length}

## Broken Links

${brokenLinksResult.broken.map((link, index) => {
  const [url, status] = link.split(' (');
  const statusCode = status?.replace(')', '') || 'unknown';
  return `${index + 1}. [${url}](https://thebasketballfactoryinc.com${url}) - Status: ${statusCode}`;
}).join('\n')}

---
*Generated by SEO Automation System*
`;
    
    fs.writeFileSync(brokenLinksPath, brokenLinksContent);
    console.log(`Broken links report saved to: ${brokenLinksPath}`);
  } else {
    console.log('\n[Step 2] No broken links found - skipping report generation');
  }
  
  // Step 3: Generate sitemap
  console.log('\n[Step 3] Generating XML sitemap...');
  const sitemapXml = await generateSitemap();
  
  if (sitemapXml) {
    console.log('Sitemap generated successfully');
    
    // Step 4: Save sitemap
    console.log('\n[Step 4] Saving sitemap to public directory...');
    const sitemapPath = '/home/ubuntu/rise_as_one_aau/nextjs_space/public/sitemap.xml';
    fs.writeFileSync(sitemapPath, sitemapXml);
    console.log(`Sitemap saved to: ${sitemapPath}`);
  } else {
    console.error('Failed to generate sitemap');
  }
  
  // Step 5: Log results
  console.log('\n[Step 5] Logging technical check results...');
  const logPath = path.join(logDir, 'technical_checks.log');
  const logEntry = `[${new Date().toISOString()}] Technical SEO Check - Pages Checked: ${brokenLinksResult.checked}, Broken Links: ${brokenLinksResult.broken.length}, Sitemap: ${sitemapXml ? 'Generated' : 'Failed'}\n`;
  
  fs.appendFileSync(logPath, logEntry);
  console.log(`Log entry added to: ${logPath}`);
  
  // Step 6: Send alert email if broken links exceed 5
  if (brokenLinksResult.broken.length > 5) {
    console.log('\n[Step 6] Broken links exceed threshold - sending alert email...');
    
    const emailContent = `
      <h2>⚠️ Technical SEO Alert: Broken Links Detected</h2>
      <p><strong>Date:</strong> ${date}</p>
      <p><strong>Total Pages Checked:</strong> ${brokenLinksResult.checked}</p>
      <p><strong>Broken Links Found:</strong> ${brokenLinksResult.broken.length}</p>
      
      <h3>Broken Links:</h3>
      <ul>
        ${brokenLinksResult.broken.map(link => {
          const [url, status] = link.split(' (');
          const statusCode = status?.replace(')', '') || 'unknown';
          return `<li><a href="https://thebasketballfactoryinc.com${url}">${url}</a> - Status: ${statusCode}</li>`;
        }).join('\n')}
      </ul>
      
      <p>Please review and fix these broken links as soon as possible.</p>
    `;
    
    try {
      await sendEmail({
        to: 'khouston@thebasketballfactorynj.com',
        subject: `🚨 Technical SEO Alert: ${brokenLinksResult.broken.length} Broken Links Detected`,
        html: emailContent
      });
      console.log('Alert email sent successfully');
    } catch (error) {
      console.error('Failed to send alert email:', error);
    }
  } else {
    console.log('\n[Step 6] Broken links below threshold - no alert email needed');
  }
  
  console.log('\n=== Technical SEO Check Complete ===');
  
  return {
    date,
    pagesChecked: brokenLinksResult.checked,
    brokenLinksFound: brokenLinksResult.broken.length,
    sitemapGenerated: !!sitemapXml
  };
}

runTechnicalSEOCheck()
  .then(result => {
    console.log('\nSummary:', result);
    process.exit(0);
  })
  .catch(error => {
    console.error('Technical SEO check failed:', error);
    process.exit(1);
  });
